set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

if(${CMAKE_BUILD_TYPE} STREQUAL "Debug")
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -g")

  if(USE_SANITIZER)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fsanitize=address")
  endif()
else()
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -O3")
endif()

find_package(PkgConfig)

pkg_check_modules(X11 REQUIRED x11)
pkg_check_modules(CAIRO REQUIRED cairo;cairo-fc)
pkg_check_modules(PANGO REQUIRED pango)
pkg_check_modules(PANGOCAIRO REQUIRED pangocairo)
pkg_check_modules(GLFW3 REQUIRED glfw3)
pkg_check_modules(GLIB REQUIRED glib-2.0;gobject-2.0;gio-2.0)
pkg_check_modules(GTK REQUIRED gtk4;atk;fribidi;epoxy;gtk4-wayland)
pkg_check_modules(FREETYPE REQUIRED freetype2)
pkg_check_modules(FONTCONFIG REQUIRED fontconfig)
pkg_check_modules(PANGOFC REQUIRED pangofc)
pkg_check_modules(FRIBID REQUIRED fribidi)
pkg_check_modules(PNG REQUIRED libpng)
pkg_check_modules(EPOXY REQUIRED epoxy)
pkg_check_modules(GDK REQUIRED gdk-3.0;gdk-wayland-3.0)
pkg_check_modules(XKBCOMMON REQUIRED xkbcommon)
pkg_check_modules(VULKAN REQUIRED vulkan)
pkg_check_modules(OPENSSL REQUIRED libssl;libcrypto)
pkg_check_modules(SSH2 REQUIRED libssh2)
pkg_check_modules(FFMPEG REQUIRED libavcodec;libavfilter;libavformat;libavutil;libswscale;libswresample)
pkg_check_modules(GSTREAMER REQUIRED gstreamer-1.0;gstreamer-video-1.0)

find_package(glad REQUIRED)
find_package(tinyexpr REQUIRED)
find_package(unity REQUIRED)
find_package(sdl3 REQUIRED)
find_package(cglm REQUIRED)
find_package(system REQUIRED)

set(MPG123_LIBRARIES "mpg123")

set(ADDTIONAL_LIBRARIES "-lpthread -lexpat -lm -lrt -lrt -luuid")
list(APPEND GTK_LIBRARIES ${ADDTIONAL_LIBRARIES})
