set(search_dirs
  ${LIBDIR}
  /usr/local
  /usr
)

FIND_PATH(GETOPT_INCLUDE_DIR
  NAMES getopt.h
  HINTS ${search_dirs}
  PATH_SUFFIXES getopt-win32/include
)

FIND_LIBRARY(GETOPT_LIBRARY
  NAMES getopt
  HINTS ${search_dirs}
  PATH_SUFFIXES lib64 lib getopt-win32/lib
)

set(GETOPT_FILES "")

IF(WIN32)
  set(GETOPT_FILE
    "getopt.dll"
  )

  FOREACH(COMPONENT ${GETOPT_FILE})
    STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)

    FIND_FILE(GETOPT_${COMPONENT}_FILE
      NAMES ${COMPONENT}
      HINTS ${search_dirs}
      PATH_SUFFIXES getopt-win32/bin
    )

    LIST(APPEND GETOPT_FILES "${GETOPT_${COMPONENT}_FILE}")
  ENDFOREACH()
ENDIF()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GETOPT DEFAULT_MSG
  GETOPT_LIBRARY GETOPT_INCLUDE_DIR)

IF(GETOPT_FOUND)
  SET(GETOPT_LIBRARIES ${GETOPT_LIBRARY})
  SET(GETOPT_INCLUDE_DIRS ${GETOPT_INCLUDE_DIR})
ENDIF(GETOPT_FOUND)

MARK_AS_ADVANCED(
  GETOPT_INCLUDE_DIR
  GETOPT_LIBRARY
)
