set(LLVM_BIN "$ENV{LLVM_BIN}")
if(NOT ${LLVM_BIN} STREQUAL "")
  STRING(REPLACE "\\" "/" LLVM_BIN ${LLVM_BIN})
endif()
set(LLVM_HOME "${LLVM_BIN}/..")

log("${LLVM_HOME}")
set(search_dirs
  ${LIBDIR}
  ${LLVM_HOME}
  /usr/local
  /usr
  /usr/lib/x86_64-linux-gnu
)

FIND_PATH(LLVM_INCLUDE_DIR
  NAMES llvm-c/Core.h
  HINTS ${search_dirs}
  PATH_SUFFIXES llvm/include include
)

set(LLVM_COMPONENTS
  clangSupport
)

FOREACH(COMPONENT ${LLVM_COMPONENTS})
  STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)

  FIND_LIBRARY(LLVM_${UPPERCOMPONENT}_LIBRARY
    NAMES ${COMPONENT}
    HINTS ${search_dirs}
    PATH_SUFFIXES lib
  )

  LIST(APPEND LLVM_LIBRARY "${LLVM_${UPPERCOMPONENT}_LIBRARY}")
ENDFOREACH()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LLVM DEFAULT_MSG
  LLVM_LIBRARY LLVM_INCLUDE_DIR)

IF(LLVM_FOUND)
  SET(LLVM_LIBRARIES ${LLVM_LIBRARY})
  SET(LLVM_INCLUDE_DIRS ${LLVM_INCLUDE_DIR})
ENDIF(LLVM_FOUND)

MARK_AS_ADVANCED(
  LLVM_INCLUDE_DIR
  LLVM_LIBRARY
)
