set(search_dirs
  ${LIBDIR}
  /usr/local
  /usr
)

FIND_PATH(SSH2_INCLUDE_DIR
  NAMES libssh2.h
  HINTS ${search_dirs}
  PATH_SUFFIXES libssh2/include
)

FIND_LIBRARY(SSH2_LIBRARY
  NAMES libssh2
  HINTS ${search_dirs}
  PATH_SUFFIXES lib64 lib libssh2/lib
)

set(SSH2_FILES "")
IF(WIN32)
  set(SSH2_FILE
    "libssh2.dll"
  )
  FOREACH(COMPONENT ${SSH2_FILE})
    STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)


    FIND_FILE(SSH2_${COMPONENT}_FILE
      NAMES ${COMPONENT}
      HINTS ${search_dirs}
      PATH_SUFFIXES libssh2/bin
    )

    LIST(APPEND SSH2_FILES "${SSH2_${COMPONENT}_FILE}")
  ENDFOREACH()
ENDIF()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SSH2 DEFAULT_MSG
  SSH2_LIBRARY SSH2_INCLUDE_DIR)

IF(SSH2_FOUND)
  SET(SSH2_LIBRARIES ${SSH2_LIBRARY})
  SET(SSH2_INCLUDE_DIRS ${SSH2_INCLUDE_DIR})
ENDIF(SSH2_FOUND)

MARK_AS_ADVANCED(
  SSH2_INCLUDE_DIR
  SSH2_LIBRARY
)
