set(search_dirs
  ${LIBDIR}
  /usr/local
  /usr
)

FIND_PATH(GCORUTINE_INCLUDE_DIR
  NAMES gcoroutine.h
  HINTS ${search_dirs}
  PATH_SUFFIXES gcoroutine/include
)

LIST(APPEND GCORUTINE_INCLUDE_DIR
  "${GCORUTINE_INCLUDE_DIR}/"
)

set(GCORUTINE_COMPONENTS
  gcoroutine
)

FOREACH(COMPONENT ${GCORUTINE_COMPONENTS})
  STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)

  FIND_LIBRARY(GCORUTINE_${UPPERCOMPONENT}_LIBRARY
    NAMES ${COMPONENT}
    HINTS ${search_dirs}
    PATH_SUFFIXES lib gcoroutine/lib
  )

  LIST(APPEND GCORUTINE_LIBRARY "${GCORUTINE_${UPPERCOMPONENT}_LIBRARY}")
ENDFOREACH()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GCORUTINE DEFAULT_MSG
  GCORUTINE_LIBRARY GCORUTINE_INCLUDE_DIR)

IF(GCORUTINE_FOUND)
  SET(GCORUTINE_LIBRARIES ${GCORUTINE_LIBRARY})
  SET(GCORUTINE_INCLUDE_DIRS ${GCORUTINE_INCLUDE_DIR})
ENDIF(GCORUTINE_FOUND)

MARK_AS_ADVANCED(
  GCORUTINE_INCLUDE_DIR
  GCORUTINE_LIBRARY
)
