set(search_dirs
  ${LIBDIR}
  /usr/local
  /usr
)

FIND_PATH(GETTEXT_INCLUDE_DIR
  NAMES libintl.h
  HINTS ${search_dirs}
  PATH_SUFFIXES gettext/include
)

FIND_LIBRARY(GETTEXT_LIBRARY
  NAMES intl
  HINTS ${search_dirs}
  PATH_SUFFIXES lib64 lib gettext/lib
)

set(GETTEXT_FILES "")
IF(WIN32)
  set(GETTEXT_FILE
    "intl-8.dll"
  )
  FOREACH(COMPONENT ${GETTEXT_FILE})
    STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)


    FIND_FILE(GETTEXT_${COMPONENT}_FILE
      NAMES ${COMPONENT}
      HINTS ${search_dirs}
      PATH_SUFFIXES gettext/bin
    )

    LIST(APPEND GETTEXT_FILES "${GETTEXT_${COMPONENT}_FILE}")
  ENDFOREACH()
ENDIF()

set(GETTEXT_DEPS
)
add_dep_for_libray_N(gettext "${GETTEXT_DEPS}")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GETTEXT DEFAULT_MSG
  GETTEXT_LIBRARY GETTEXT_INCLUDE_DIR)

IF(GETTEXT_FOUND)
  SET(GETTEXT_LIBRARIES ${GETTEXT_LIBRARY})
  SET(GETTEXT_INCLUDE_DIRS ${GETTEXT_INCLUDE_DIR})
ENDIF(GETTEXT_FOUND)

MARK_AS_ADVANCED(
  GETTEXT_INCLUDE_DIR
  GETTEXT_LIBRARY
)
