set(search_dirs
  ${LIBDIR}
  /usr/local
  /usr
  /usr/lib/x86_64-linux-gnu
)

FIND_PATH(NANOMSG_INCLUDE_DIR
  NAMES nanomsg/nn.h
  HINTS ${search_dirs}
  PATH_SUFFIXES nanomsg/include
)

set(NANOMSG_COMPONENTS
  nanomsg
)

FOREACH(COMPONENT ${NANOMSG_COMPONENTS})
  STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)

  FIND_LIBRARY(NANOMSG_${UPPERCOMPONENT}_LIBRARY
    NAMES ${COMPONENT}
    HINTS ${search_dirs}
    PATH_SUFFIXES lib64 lib
  )

  LIST(APPEND NANOMSG_LIBRARY "${NANOMSG_${UPPERCOMPONENT}_LIBRARY}")
ENDFOREACH()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(NANOMSG DEFAULT_MSG
  NANOMSG_LIBRARY NANOMSG_INCLUDE_DIR)

IF(NANOMSG_FOUND)
  SET(NANOMSG_LIBRARIES ${NANOMSG_LIBRARY})
  SET(NANOMSG_INCLUDE_DIRS ${NANOMSG_INCLUDE_DIR})
ENDIF(NANOMSG_FOUND)

MARK_AS_ADVANCED(
  NANOMSG_INCLUDE_DIR
  NANOMSG_LIBRARY
)
