set(search_dirs
  ${LIBDIR}
  /usr/local
  /usr
)

FIND_PATH(BZIP2_INCLUDE_DIR
  NAMES bzlib.h
  HINTS ${search_dirs}
  PATH_SUFFIXES bzip2/include
)

FIND_LIBRARY(BZIP2_LIBRARY
  NAMES bz2.lib
  HINTS ${search_dirs}
  PATH_SUFFIXES lib64 lib bzip2/lib
)

set(BZIP2_FILES "")
IF(WIN32)
  set(BZIP2_FILE
    "bz2.dll"
  )
  FOREACH(COMPONENT ${BZIP2_FILE})
    STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)


    FIND_FILE(BZIP2_${COMPONENT}_FILE
      NAMES ${COMPONENT}
      HINTS ${search_dirs}
      PATH_SUFFIXES bzip2/bin
    )

    LIST(APPEND BZIP2_FILES "${BZIP2_${COMPONENT}_FILE}")
  ENDFOREACH()
ENDIF()

set(BZIP2_DEPS
   
)
add_dep_for_libray_N(bzip2 "${BZIP2_DEPS}")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(BZIP2 DEFAULT_MSG
  BZIP2_LIBRARY BZIP2_INCLUDE_DIR)

IF(BZIP2_FOUND)
  SET(BZIP2_LIBRARIES ${BZIP2_LIBRARY})
  SET(BZIP2_INCLUDE_DIRS ${BZIP2_INCLUDE_DIR})
ENDIF(BZIP2_FOUND)

MARK_AS_ADVANCED(
  BZIP2_INCLUDE_DIR
  BZIP2_LIBRARY
)

