set(search_dirs
  ${LIBDIR}
  /usr/local
  /usr
  /usr/lib/x86_64-linux-gnu
)

FIND_PATH(CZMQ_INCLUDE_DIR
  NAMES czmq.h
  HINTS ${search_dirs}
  PATH_SUFFIXES czmq/include
)

set(CZMQ_COMPONENTS
  czmq
  libzmq-mt-4_3_4
)

FOREACH(COMPONENT ${CZMQ_COMPONENTS})
  STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)

  FIND_LIBRARY(CZMQ_${UPPERCOMPONENT}_LIBRARY
    NAMES ${COMPONENT}
    HINTS ${search_dirs}
    PATH_SUFFIXES lib64 lib
  )

  LIST(APPEND CZMQ_LIBRARY "${CZMQ_${UPPERCOMPONENT}_LIBRARY}")
ENDFOREACH()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CZMQ DEFAULT_MSG
  CZMQ_LIBRARY CZMQ_INCLUDE_DIR)

IF(CZMQ_FOUND)
  SET(CZMQ_LIBRARIES ${CZMQ_LIBRARY})
  SET(CZMQ_INCLUDE_DIRS ${CZMQ_INCLUDE_DIR})
ENDIF(CZMQ_FOUND)

MARK_AS_ADVANCED(
  CZMQ_INCLUDE_DIR
  CZMQ_LIBRARY
)
