set(search_dirs
  ${LIBDIR}
  /usr/local
  /usr
)

FIND_PATH(LIBEPOXY_INCLUDE_DIR
  NAMES epoxy/gl_generated.h
  HINTS ${search_dirs}
  PATH_SUFFIXES libepoxy/include
)

FIND_LIBRARY(LIBEPOXY_LIBRARY
  NAMES epoxy.lib
  HINTS ${search_dirs}
  PATH_SUFFIXES lib64 lib libepoxy/lib
)

set(LIBEPOXY_FILES "")
IF(WIN32)
  set(LIBEPOXY_FILE
    "epoxy-0.dll"
  )
  FOREACH(COMPONENT ${LIBEPOXY_FILE})
    STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)


    FIND_FILE(LIBEPOXY_${COMPONENT}_FILE
      NAMES ${COMPONENT}
      HINTS ${search_dirs}
      PATH_SUFFIXES libepoxy/bin
    )

    LIST(APPEND LIBEPOXY_FILES "${LIBEPOXY_${COMPONENT}_FILE}")
  ENDFOREACH()
ENDIF()

set(LIBEPOXY_DEPS
)
add_dep_for_libray_N(libepoxy "${LIBEPOXY_DEPS}")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBEPOXY DEFAULT_MSG
  LIBEPOXY_LIBRARY LIBEPOXY_INCLUDE_DIR)

IF(LIBEPOXY_FOUND)
  SET(LIBEPOXY_LIBRARIES ${LIBEPOXY_LIBRARY})
  SET(LIBEPOXY_INCLUDE_DIRS ${LIBEPOXY_INCLUDE_DIR})
ENDIF(LIBEPOXY_FOUND)

MARK_AS_ADVANCED(
  LIBEPOXY_INCLUDE_DIR
  LIBEPOXY_LIBRARY
)

