set(search_dirs
  ${LIBDIR}
  /usr/local
  /usr
  /usr/lib/x86_64-linux-gnu/
)

FIND_PATH(GLFW3_INCLUDE_DIR
  NAMES GLFW/glfw3.h
  HINTS ${search_dirs}
  PATH_SUFFIXES include glfw3/include
)
LIST(APPEND GLFW3_INCLUDE_DIR "${GLAD_INCLUDE_DIRS}")

FIND_LIBRARY(GLFW3_LIBRARY
  NAMES glfw glfw3
  HINTS ${search_dirs}
  PATH_SUFFIXES lib64 glfw3/lib lib
)

if(WIN32)
  set(GLFW3_FILE_COMPONENTS
    "glfw3.dll")

  FIND_LIBRARY(GLFW3_LIBRARY
    NAMES glfw3
    HINTS ${search_dirs}
    PATH_SUFFIXES pthreads/lib lib64 lib)

  FOREACH(COMPONENT ${GLFW3_FILE_COMPONENTS})
    STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)

    FIND_FILE(GLFW3_${COMPONENT}_FILE
      NAMES ${COMPONENT}
      HINTS ${search_dirs}
      PATH_SUFFIXES glfw3/bin
      )

    LIST(APPEND GLFW3_FILES "${GLFW3_${COMPONENT}_FILE}")
  ENDFOREACH()
endif()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GLFW3 DEFAULT_MSG
  GLFW3_LIBRARY GLFW3_INCLUDE_DIR)

IF(GLFW3_FOUND)
  SET(GLFW3_LIBRARIES ${GLFW3_LIBRARY})
  SET(GLFW3_INCLUDE_DIRS ${GLFW3_INCLUDE_DIR})
ENDIF(GLFW3_FOUND)

MARK_AS_ADVANCED(
  GLFW3_INCLUDE_DIR
  GLFW3_LIBRARY
)
