set(search_dirs
  ${LIBDIR}
  /usr/local
  /usr
  /usr/lib/x86_64-linux-gnu
)

FIND_PATH(CLANG_INCLUDE_DIR
  NAMES clang-c/ExternC.h
  HINTS ${search_dirs}
  PATH_SUFFIXES clang/include include
)

set(CLANG_COMPONENTS
  libclang
)

FOREACH(COMPONENT ${CLANG_COMPONENTS})
  STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)

  FIND_LIBRARY(CLANG_${UPPERCOMPONENT}_LIBRARY
    NAMES ${COMPONENT}
    HINTS ${search_dirs}
    PATH_SUFFIXES lib
  )

  LIST(APPEND CLANG_LIBRARY "${CLANG_${UPPERCOMPONENT}_LIBRARY}")
ENDFOREACH()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CLANG DEFAULT_MSG
  CLANG_LIBRARY CLANG_INCLUDE_DIR)

IF(CLANG_FOUND)
  SET(CLANG_LIBRARIES ${CLANG_LIBRARY})
  SET(CLANG_INCLUDE_DIRS ${CLANG_INCLUDE_DIR})
ENDIF(CLANG_FOUND)

MARK_AS_ADVANCED(
  CLANG_INCLUDE_DIR
  CLANG_LIBRARY
)
