set(search_dirs
  ${LIBDIR}
  /usr/local
  /usr
)

FIND_PATH(GRAPHENE_INCLUDE_DIR
  NAMES graphene.h
  HINTS ${search_dirs}
  PATH_SUFFIXES graphene/include/graphene-1.0
)

FIND_LIBRARY(GRAPHENE_LIBRARY
  NAMES graphene-1.0.lib
  HINTS ${search_dirs}
  PATH_SUFFIXES lib64 lib graphene/lib
)

set(GRAPHENE_FILES "")
IF(WIN32)
  set(GRAPHENE_FILE
    "graphene-1.0-0.dll"
  )
  FOREACH(COMPONENT ${GRAPHENE_FILE})
    STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)


    FIND_FILE(GRAPHENE_${COMPONENT}_FILE
      NAMES ${COMPONENT}
      HINTS ${search_dirs}
      PATH_SUFFIXES graphene/bin
    )

    LIST(APPEND GRAPHENE_FILES "${GRAPHENE_${COMPONENT}_FILE}")
  ENDFOREACH()
ENDIF()

set(GRAPHENE_DEPS
  gettext
  glib
)
add_dep_for_libray_N(graphene "${GRAPHENE_DEPS}")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GRAPHENE DEFAULT_MSG
  GRAPHENE_LIBRARY GRAPHENE_INCLUDE_DIR)

IF(GRAPHENE_FOUND)
  SET(GRAPHENE_LIBRARIES ${GRAPHENE_LIBRARY})
  SET(GRAPHENE_INCLUDE_DIRS ${GRAPHENE_INCLUDE_DIR})
ENDIF(GRAPHENE_FOUND)

MARK_AS_ADVANCED(
  GRAPHENE_INCLUDE_DIR
  GRAPHENE_LIBRARY
)

