set(search_dirs
  ${LIBDIR}
  /usr/local
  /usr
)

FIND_PATH(GLAD_INCLUDE_DIR
  NAMES glad.h
  HINTS ${search_dirs}
  PATH_SUFFIXES glad/include
)

FIND_LIBRARY(GLAD_LIBRARY
  NAMES glad
  HINTS ${search_dirs}
  PATH_SUFFIXES lib64 glad/lib
)

if(WIN32)
  LIST(APPEND GLAD_LIBRARY "opengl32.lib")
endif()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GLAD DEFAULT_MSG
  GLAD_LIBRARY GLAD_INCLUDE_DIR)

IF(GLAD_FOUND)
  SET(GLAD_LIBRARIES ${GLAD_LIBRARY})
  SET(GLAD_INCLUDE_DIRS ${GLAD_INCLUDE_DIR})
ENDIF(GLAD_FOUND)

MARK_AS_ADVANCED(
  GLAD_INCLUDE_DIR
  GLAD_LIBRARY
)
