set(search_dirs
  ${LIBDIR}
  /usr/local
  /usr
)

FIND_PATH(STB_INCLUDE_DIR
  NAMES stb_image.h
  HINTS ${search_dirs}
  PATH_SUFFIXES stb/include
)

FIND_LIBRARY(STB_LIBRARY
  NAMES stb
  HINTS ${search_dirs}
  PATH_SUFFIXES lib64 lib stb/lib
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(STB DEFAULT_MSG
  STB_LIBRARY STB_INCLUDE_DIR)

IF(STB_FOUND)
  SET(STB_LIBRARIES ${STB_LIBRARY})
  SET(STB_INCLUDE_DIRS ${STB_INCLUDE_DIR})
ENDIF(STB_FOUND)

MARK_AS_ADVANCED(
  STB_INCLUDE_DIR
  STB_LIBRARY
)
