set(search_dirs
  ${LIBDIR}
  /usr/local
  /usr
)

FIND_PATH(LIBICONV_INCLUDE_DIR
  NAMES iconv.h
  HINTS ${search_dirs}
  PATH_SUFFIXES libiconv/include
)

FIND_LIBRARY(LIBICONV_LIBRARY
  NAMES iconv.lib
  HINTS ${search_dirs}
  PATH_SUFFIXES lib64 lib libiconv/lib
)

set(LIBICONV_FILES "")
IF(WIN32)
  set(LIBICONV_FILE
    "charset-1.dll"
    "iconv-2.dll"
  )
  FOREACH(COMPONENT ${LIBICONV_FILE})
    STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)


    FIND_FILE(LIBICONV_${COMPONENT}_FILE
      NAMES ${COMPONENT}
      HINTS ${search_dirs}
      PATH_SUFFIXES libiconv/bin
    )

    LIST(APPEND LIBICONV_FILES "${LIBICONV_${COMPONENT}_FILE}")
  ENDFOREACH()
ENDIF()

set(LIBICONV_DEPS
   
)
add_dep_for_libray_N(libiconv "${LIBICONV_DEPS}")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBICONV DEFAULT_MSG
  LIBICONV_LIBRARY LIBICONV_INCLUDE_DIR)

IF(LIBICONV_FOUND)
  SET(LIBICONV_LIBRARIES ${LIBICONV_LIBRARY})
  SET(LIBICONV_INCLUDE_DIRS ${LIBICONV_INCLUDE_DIR})
ENDIF(LIBICONV_FOUND)

MARK_AS_ADVANCED(
  LIBICONV_INCLUDE_DIR
  LIBICONV_LIBRARY
)

