set(search_dirs
  ${LIBDIR}
  /usr/local
  /usr
  /usr/lib/x86_64-linux-gnu
  )

FIND_PATH(OPENSSL_INCLUDE_DIR
  NAMES openssl/ssl.h
  HINTS ${search_dirs}
  PATH_SUFFIXES openssl/include include
  )

set(OPENSSL_COMPONENTS
  libssl
  libcrypto)

FOREACH(COMPONENT ${OPENSSL_COMPONENTS})
  STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)

  FIND_LIBRARY(OPENSSL_${UPPERCOMPONENT}_LIBRARY
    NAMES ${COMPONENT}
    HINTS ${search_dirs}
    PATH_SUFFIXES openssl/lib)

  LIST(APPEND OPENSSL_LIBRARY "${OPENSSL_${UPPERCOMPONENT}_LIBRARY}")
ENDFOREACH()

if(WIN32)
  set(OPENSSL_FILES "")
  set(OPENSSL_FILE_COMPONENTS
    "libssl-3-x64.dll"
    "libcrypto-3-x64.dll"
    "legacy.dll")

  FOREACH(COMPONENT ${OPENSSL_FILE_COMPONENTS})
    STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)

    FIND_FILE(OPENSSL_${COMPONENT}_FILE
      NAMES ${COMPONENT}
      HINTS ${search_dirs}
      PATH_SUFFIXES openssl/bin
      )

    LIST(APPEND OPENSSL_FILES "${OPENSSL_${COMPONENT}_FILE}")
  ENDFOREACH()
endif()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OPENSSL DEFAULT_MSG
  OPENSSL_LIBRARY OPENSSL_INCLUDE_DIR)

IF(OPENSSL_FOUND)
  SET(OPENSSL_LIBRARIES ${OPENSSL_LIBRARY})
  SET(OPENSSL_INCLUDE_DIRS ${OPENSSL_INCLUDE_DIR})
ENDIF(OPENSSL_FOUND)

MARK_AS_ADVANCED(
  OPENSSL_INCLUDE_DIR
  OPENSSL_LIBRARY
)
