set(search_dirs
  ${LIBDIR}
  /usr/local
  /usr
  /usr/lib/x86_64-linux-gnu
)

FIND_PATH(TINYEXPR_INCLUDE_DIR
  NAMES tinyexpr.h
  HINTS ${search_dirs}
  PATH_SUFFIXES tinyexpr/include
)

FIND_LIBRARY(TINYEXPR_LIBRARY
  NAMES tinyexpr
  HINTS ${search_dirs}
  PATH_SUFFIXES lib64 lib tinyexpr/lib
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(TINYEXPR DEFAULT_MSG
  TINYEXPR_LIBRARY TINYEXPR_INCLUDE_DIR)

IF(TINYEXPR_FOUND)
  SET(TINYEXPR_LIBRARIES ${TINYEXPR_LIBRARY})
  SET(TINYEXPR_INCLUDE_DIRS ${TINYEXPR_INCLUDE_DIR})
ENDIF(TINYEXPR_FOUND)

MARK_AS_ADVANCED(
  TINYEXPR_INCLUDE_DIR
  TINYEXPR_LIBRARY
)
