
set(search_dirs
  ${LIBDIR}
  /usr/local
  /usr
)

FIND_PATH(VKVG_INCLUDE_DIR
  NAMES vkvg.h
  HINTS ${search_dirs}
  PATH_SUFFIXES vkvg/include
)

LIST(APPEND VKVG_INCLUDE_DIR
  "${VKVG_INCLUDE_DIR}/vkh"
)

set(VKVG_COMPONENTS
  vkvg
  vkh
  glutess
)

FOREACH(COMPONENT ${VKVG_COMPONENTS})
  STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)

  FIND_LIBRARY(VKVG_${UPPERCOMPONENT}_LIBRARY
    NAMES ${COMPONENT}
    HINTS ${search_dirs}
    PATH_SUFFIXES lib vkvg/lib
  )

  LIST(APPEND VKVG_LIBRARY "${VKVG_${UPPERCOMPONENT}_LIBRARY}")
ENDFOREACH()

if (UNIX)
  LIST(APPEND VKVG_LIBRARY
  "-lstdc++"
  "freetype"
  "fontconfig"
  "z"
)
endif()


INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(VKVG DEFAULT_MSG
  VKVG_LIBRARY VKVG_INCLUDE_DIR)

IF(VKVG_FOUND)
  SET(VKVG_LIBRARIES ${VKVG_LIBRARY})
  SET(VKVG_INCLUDE_DIRS ${VKVG_INCLUDE_DIR})
ENDIF(VKVG_FOUND)

MARK_AS_ADVANCED(
  VKVG_INCLUDE_DIR
  VKVG_LIBRARY
)
