set(search_dirs
  ${LIBDIR}
  /usr/local
  /usr
)

FIND_PATH(LIBDWARF_INCLUDE_DIR
  NAMES libdwarf/libdwarf.h
  HINTS ${search_dirs}
  PATH_SUFFIXES libdwarf/include
)

FIND_LIBRARY(LIBDWARF_LIBRARY
  NAMES dwarf.lib
  HINTS ${search_dirs}
  PATH_SUFFIXES lib64 lib libdwarf/lib
)

set(LIBDWARF_FILES "")
IF(WIN32)
  set(LIBDWARF_FILE
  )
  FOREACH(COMPONENT ${LIBDWARF_FILE})
    STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)


    FIND_FILE(LIBDWARF_${COMPONENT}_FILE
      NAMES ${COMPONENT}
      HINTS ${search_dirs}
      PATH_SUFFIXES libdwarf/bin
    )

    LIST(APPEND LIBDWARF_FILES "${LIBDWARF_${COMPONENT}_FILE}")
  ENDFOREACH()
ENDIF()

set(LIBDWARF_DEPS
   
)
add_dep_for_libray_N(libdwarf "${LIBDWARF_DEPS}")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBDWARF DEFAULT_MSG
  LIBDWARF_LIBRARY LIBDWARF_INCLUDE_DIR)

IF(LIBDWARF_FOUND)
  SET(LIBDWARF_LIBRARIES ${LIBDWARF_LIBRARY})
  SET(LIBDWARF_INCLUDE_DIRS ${LIBDWARF_INCLUDE_DIR})
ENDIF(LIBDWARF_FOUND)

MARK_AS_ADVANCED(
  LIBDWARF_INCLUDE_DIR
  LIBDWARF_LIBRARY
)


