set(search_dirs
  ${LIBDIR}
  /usr/local
  /usr
)

FIND_PATH(LIBUNWIND_INCLUDE_DIR
  NAMES libunwind.h
  HINTS ${search_dirs}
  PATH_SUFFIXES libunwind/include
)

FIND_LIBRARY(LIBUNWIND_LIBRARY
  NAMES unwind
  HINTS ${search_dirs}
  PATH_SUFFIXES lib64 lib libunwind/lib
)

set(LIBUNWIND_FILES "")
IF(WIN32)
  set(LIBUNWIND_FILE
    "unwind.dll"
  )
  FOREACH(COMPONENT ${LIBUNWIND_FILE})
    STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)


    FIND_FILE(LIBUNWIND_${COMPONENT}_FILE
      NAMES ${COMPONENT}
      HINTS ${search_dirs}
      PATH_SUFFIXES libunwind/bin
    )

    LIST(APPEND LIBUNWIND_FILES "${LIBUNWIND_${COMPONENT}_FILE}")
  ENDFOREACH()
ENDIF()

set(LIBUNWIND_DEPS
)
add_dep_for_libray_N(libunwind "${LIBUNWIND_DEPS}")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBUNWIND DEFAULT_MSG
  LIBUNWIND_LIBRARY LIBUNWIND_INCLUDE_DIR)

IF(LIBUNWIND_FOUND)
  SET(LIBUNWIND_LIBRARIES ${LIBUNWIND_LIBRARY})
  SET(LIBUNWIND_INCLUDE_DIRS ${LIBUNWIND_INCLUDE_DIR})
ENDIF(LIBUNWIND_FOUND)

MARK_AS_ADVANCED(
  LIBUNWIND_INCLUDE_DIR
  LIBUNWIND_LIBRARY
)


