set(SYS_SEARCH_DIRS "$ENV{VULKAN_SDK}")
if(NOT ${SYS_SEARCH_DIRS} STREQUAL "")
  STRING(REPLACE "\\" "/" SYS_SEARCH_DIRS ${SYS_SEARCH_DIRS})
endif()

set(search_dirs
  ${SYS_SEARCH_DIRS}
  ${LIBDIR}
  /usr/local
  /usr
  /usr/lib/x86_64-linux-gnu
)

FIND_PATH(VULKAN_INCLUDE_DIR
  NAMES vulkan/vulkan.h
  HINTS ${search_dirs}
  PATH_SUFFIXES include
)

set(VULKAN_COMPONENTS
  vulkan-1
)

FOREACH(COMPONENT ${VULKAN_COMPONENTS})
  STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)

  FIND_LIBRARY(VULKAN_${UPPERCOMPONENT}_LIBRARY
    NAMES ${COMPONENT}
    HINTS ${search_dirs}
    PATH_SUFFIXES lib lib64
  )

  LIST(APPEND VULKAN_LIBRARY "${VULKAN_${UPPERCOMPONENT}_LIBRARY}")
ENDFOREACH()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(VULKAN DEFAULT_MSG
  VULKAN_LIBRARY VULKAN_INCLUDE_DIR)

IF(VULKAN_FOUND)
  SET(VULKAN_LIBRARIES ${VULKAN_LIBRARY})
  SET(VULKAN_INCLUDE_DIRS ${VULKAN_INCLUDE_DIR})
ENDIF(VULKAN_FOUND)

MARK_AS_ADVANCED(
  VULKAN_INCLUDE_DIR
  VULKAN_LIBRARY
)
