set(search_dirs
  ${LIBDIR}
  /usr/local
  /usr
)

FIND_PATH(NANOVG_INCLUDE_DIR
  NAMES nanovg_gl.h
  HINTS ${search_dirs}
  PATH_SUFFIXES nanovg/include
)

FIND_LIBRARY(NANOVG_LIBRARY
  NAMES nanovg.lib
  HINTS ${search_dirs}
  PATH_SUFFIXES lib64 lib nanovg/lib
)

set(NANOVG_FILES "")
IF(WIN32)
  set(NANOVG_FILE
    
  )
  FOREACH(COMPONENT ${NANOVG_FILE})
    STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)


    FIND_FILE(NANOVG_${COMPONENT}_FILE
      NAMES ${COMPONENT}
      HINTS ${search_dirs}
      PATH_SUFFIXES nanovg/bin
    )

    LIST(APPEND NANOVG_FILES "${NANOVG_${COMPONENT}_FILE}")
  ENDFOREACH()
ENDIF()

set(NANOVG_DEPS
   
)
add_dep_for_libray_N(nanovg "${NANOVG_DEPS}")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(NANOVG DEFAULT_MSG
  NANOVG_LIBRARY NANOVG_INCLUDE_DIR)

IF(NANOVG_FOUND)
  SET(NANOVG_LIBRARIES ${NANOVG_LIBRARY})
  SET(NANOVG_INCLUDE_DIRS ${NANOVG_INCLUDE_DIR})
ENDIF(NANOVG_FOUND)

MARK_AS_ADVANCED(
  NANOVG_INCLUDE_DIR
  NANOVG_LIBRARY
)
