set(search_dirs
  ${LIBDIR}
  /usr/local
  /usr
  /usr/lib/x86_64-linux-gnu
)

FIND_PATH(UNITY_INCLUDE_DIR
  NAMES Unity/unity.h
  HINTS ${search_dirs}
  PATH_SUFFIXES Unity/include
)

FIND_LIBRARY(UNITY_LIBRARY
  NAMES Unity
  HINTS ${search_dirs}
  PATH_SUFFIXES lib64 Unity/lib
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(UNITY DEFAULT_MSG
  UNITY_LIBRARY UNITY_INCLUDE_DIR)

IF(UNITY_FOUND)
  SET(UNITY_LIBRARIES ${UNITY_LIBRARY})
  SET(UNITY_INCLUDE_DIRS ${UNITY_INCLUDE_DIR})
ENDIF(UNITY_FOUND)

MARK_AS_ADVANCED(
  UNITY_INCLUDE_DIR
  UNITY_LIBRARY
)
