set(search_dirs
  ${LIBDIR}
  /usr/local
  /usr
)

FIND_PATH(JPEGTURBO_INCLUDE_DIR
  NAMES jpeglib.h
  HINTS ${search_dirs}
  PATH_SUFFIXES libjpegturbo/include
)

FIND_LIBRARY(JPEGTURBO_LIBRARY
  NAMES jpeg
  HINTS ${search_dirs}
  PATH_SUFFIXES lib64 lib libjpegturbo/lib
)

set(JPEGTURBO_FILES "")
IF(WIN32)
  set(JPEGTURBO_FILE
    "jpeg62.dll"
    "turbojpeg.dll"
  )
  FOREACH(COMPONENT ${JPEGTURBO_FILE})
    STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)


    FIND_FILE(JPEGTURBO_${COMPONENT}_FILE
      NAMES ${COMPONENT}
      HINTS ${search_dirs}
      PATH_SUFFIXES libjpegturbo/bin
    )

    LIST(APPEND JPEGTURBO_FILES "${JPEGTURBO_${COMPONENT}_FILE}")
  ENDFOREACH()
ENDIF()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(JPEGTURBO DEFAULT_MSG
  JPEGTURBO_LIBRARY JPEGTURBO_INCLUDE_DIR)

IF(JPEGTURBO_FOUND)
  SET(JPEGTURBO_LIBRARIES ${JPEGTURBO_LIBRARY})
  SET(JPEGTURBO_INCLUDE_DIRS ${JPEGTURBO_INCLUDE_DIR})
ENDIF(JPEGTURBO_FOUND)

MARK_AS_ADVANCED(
  JPEGTURBO_INCLUDE_DIR
  JPEGTURBO_LIBRARY
)

