set(search_dirs
  ${LIBDIR}
  /usr/local
  /usr
)

FIND_PATH(SQLITE3_INCLUDE_DIR
  NAMES sqlite3ext.h
  HINTS ${search_dirs}
  PATH_SUFFIXES sqlite3/include
)

FIND_LIBRARY(SQLITE3_LIBRARY
  NAMES sqlite3.lib
  HINTS ${search_dirs}
  PATH_SUFFIXES lib64 lib sqlite3/lib
)

set(SQLITE3_FILES "")
IF(WIN32)
  set(SQLITE3_FILE
    "sqlite3.dll"
  )
  FOREACH(COMPONENT ${SQLITE3_FILE})
    STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)


    FIND_FILE(SQLITE3_${COMPONENT}_FILE
      NAMES ${COMPONENT}
      HINTS ${search_dirs}
      PATH_SUFFIXES sqlite3/bin
    )

    LIST(APPEND SQLITE3_FILES "${SQLITE3_${COMPONENT}_FILE}")
  ENDFOREACH()
ENDIF()

set(SQLITE3_DEPS
)
add_dep_for_libray_N(sqlite3 "${SQLITE3_DEPS}")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SQLITE3 DEFAULT_MSG
  SQLITE3_LIBRARY SQLITE3_INCLUDE_DIR)

IF(SQLITE3_FOUND)
  SET(SQLITE3_LIBRARIES ${SQLITE3_LIBRARY})
  SET(SQLITE3_INCLUDE_DIRS ${SQLITE3_INCLUDE_DIR})
ENDIF(SQLITE3_FOUND)

MARK_AS_ADVANCED(
  SQLITE3_INCLUDE_DIR
  SQLITE3_LIBRARY
)


