set(search_dirs
  ${LIBDIR}
  /usr/local
  /usr
)

FIND_PATH(LIBFFI_INCLUDE_DIR
  NAMES ffitarget.h
  HINTS ${search_dirs}
  PATH_SUFFIXES libffi/include
)

FIND_LIBRARY(LIBFFI_LIBRARY
  NAMES libffi.lib
  HINTS ${search_dirs}
  PATH_SUFFIXES lib64 lib libffi/lib
)

set(LIBFFI_FILES "")
IF(WIN32)
  set(LIBFFI_FILE
    "libffi.dll"
  )
  FOREACH(COMPONENT ${LIBFFI_FILE})
    STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)


    FIND_FILE(LIBFFI_${COMPONENT}_FILE
      NAMES ${COMPONENT}
      HINTS ${search_dirs}
      PATH_SUFFIXES libffi/bin
    )

    LIST(APPEND LIBFFI_FILES "${LIBFFI_${COMPONENT}_FILE}")
  ENDFOREACH()
ENDIF()

set(LIBFFI_DEPS
)
add_dep_for_libray_N(libffi "${LIBFFI_DEPS}")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBFFI DEFAULT_MSG
  LIBFFI_LIBRARY LIBFFI_INCLUDE_DIR)

IF(LIBFFI_FOUND)
  SET(LIBFFI_LIBRARIES ${LIBFFI_LIBRARY})
  SET(LIBFFI_INCLUDE_DIRS ${LIBFFI_INCLUDE_DIR})
ENDIF(LIBFFI_FOUND)

MARK_AS_ADVANCED(
  LIBFFI_INCLUDE_DIR
  LIBFFI_LIBRARY
)

