set(search_dirs
  ${LIBDIR}
  /usr/local
  /usr
)

FIND_PATH(SDL2_INCLUDE_DIR
  NAMES SDL2/SDL.h
  HINTS ${search_dirs}
  PATH_SUFFIXES sdl2/include
)

FIND_LIBRARY(SDL2_LIBRARY
  NAMES SDL2.lib
  HINTS ${search_dirs}
  PATH_SUFFIXES lib64 lib sdl2/lib
)

set(SDL2_FILES "")
IF(WIN32)
  set(SDL2_FILE
    "SDL2.dll"
  )
  FOREACH(COMPONENT ${SDL2_FILE})
    STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)

    FIND_FILE(SDL2_${COMPONENT}_FILE
      NAMES ${COMPONENT}
      HINTS ${search_dirs}
      PATH_SUFFIXES sdl2/bin
    )

    LIST(APPEND SDL2_FILES "${SDL2_${COMPONENT}_FILE}")
  ENDFOREACH()
ENDIF()

set(SDL2_DEPS
)
add_dep_for_libray_N(sdl2 "${SDL2_DEPS}")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2 DEFAULT_MSG
  SDL2_LIBRARY SDL2_INCLUDE_DIR)

IF(SDL2_FOUND)
  SET(SDL2_LIBRARIES ${SDL2_LIBRARY})
  SET(SDL2_INCLUDE_DIRS ${SDL2_INCLUDE_DIR})
ENDIF(SDL2_FOUND)

MARK_AS_ADVANCED(
  SDL2_INCLUDE_DIR
  SDL2_LIBRARY
)

