set(search_dirs
  ${LIBDIR}
  /usr/local
  /usr
)

FIND_PATH(ICONV_INCLUDE_DIR
  NAMES iconv.h
  HINTS ${search_dirs}
  PATH_SUFFIXES libiconv/include
)

FIND_LIBRARY(ICONV_LIBRARY
  NAMES iconv
  HINTS ${search_dirs}
  PATH_SUFFIXES lib64 lib libiconv/lib
)

set(ICONV_FILES "")
IF(WIN32)
  set(ICONV_FILE
    "charset-1.dll"
    "iconv-2.dll"
  )
  FOREACH(COMPONENT ${ICONV_FILE})
    STRING(TOUPPER ${COMPONENT} UPPERCOMPONENT)


    FIND_FILE(ICONV_${COMPONENT}_FILE
      NAMES ${COMPONENT}
      HINTS ${search_dirs}
      PATH_SUFFIXES libiconv/bin
    )

    LIST(APPEND ICONV_FILES "${ICONV_${COMPONENT}_FILE}")
  ENDFOREACH()
ENDIF()

set(ICONV_DEPS
   
)
add_dep_for_libray_N(libiconv "${ICONV_DEPS}")

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ICONV DEFAULT_MSG
  ICONV_LIBRARY ICONV_INCLUDE_DIR)

IF(ICONV_FOUND)
  SET(ICONV_LIBRARIES ${ICONV_LIBRARY})
  SET(ICONV_INCLUDE_DIRS ${ICONV_INCLUDE_DIR})
ENDIF(ICONV_FOUND)

MARK_AS_ADVANCED(
  ICONV_INCLUDE_DIR
  ICONV_LIBRARY
)

