set(search_dirs
  ${LIBDIR}
  /usr/local
  /usr
  /usr/lib/x86_64-linux-gnu
)

FIND_PATH(BDWGC_INCLUDE_DIR
  NAMES gc.h
  HINTS ${search_dirs}
  PATH_SUFFIXES bdwgc/include include
)

FIND_LIBRARY(BDWGC_LIBRARY
  NAMES gc
  HINTS ${search_dirs}
  PATH_SUFFIXES lib64 lib
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(BDWGC DEFAULT_MSG
  BDWGC_LIBRARY BDWGC_INCLUDE_DIR)

IF(BDWGC_FOUND)
  SET(BDWGC_LIBRARIES ${BDWGC_LIBRARY})
  SET(BDWGC_INCLUDE_DIRS ${BDWGC_INCLUDE_DIR})
ENDIF(BDWGC_FOUND)

MARK_AS_ADVANCED(
  BDWGC_INCLUDE_DIR
  BDWGC_LIBRARY
)
